version: '3.0'
services:
  bell_view_go:
    container_name: "orange_message_service"
    build:
      context: ./
    ports:
      - "1235:1234"
    networks:
      - orange_message_service-net
networks:
  orange_message_service-net:
    external: true
